In [46]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("data.csv")

# See first 5 rows
df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,2024-01-01 00:00:00,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,...,1.68,11.02,76.22,0.53,168.11,0.0,0.0,9.49,974.89,0.20
1,2024-01-01 01:00:00,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,...,2.00,10.96,76.29,0.52,168.11,0.0,0.0,9.54,974.86,0.21
2,2024-01-01 02:00:00,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,...,3.87,10.89,76.27,0.54,177.42,0.0,0.0,9.66,974.89,0.20
3,2024-01-01 03:00:00,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,...,4.02,10.84,76.16,0.52,182.27,0.0,0.0,9.69,974.85,0.20
4,2024-01-01 04:00:00,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,...,2.22,10.78,76.14,0.66,167.64,0.0,0.0,9.64,974.72,0.19

In [47]:
df.shape

(8784, 25)

In [48]:
df.info

<bound method DataFrame.info of                 Timestamp  PM2.5 (µg/m³)  PM10 (µg/m³)  NO (µg/m³)  \
0     2024-01-01 00:00:00         171.80        271.46       15.74
1     2024-01-01 01:00:00         169.67        266.77       16.18
2     2024-01-01 02:00:00         164.49        257.12       16.55
3     2024-01-01 03:00:00         162.01        252.37       15.37
4     2024-01-01 04:00:00         159.34        252.60       15.66
...                   ...            ...           ...         ...
8779  2024-12-31 19:00:00         198.61        321.53       27.89
8780  2024-12-31 20:00:00         197.96        329.01       43.13
8781  2024-12-31 21:00:00         208.68        351.64       51.96
8782  2024-12-31 22:00:00         227.68        374.71       61.51
8783  2024-12-31 23:00:00         246.06        391.50       71.77

      NO2 (µg/m³)  NOx (ppb)  NH3 (µg/m³)  SO2 (µg/m³)  CO (mg/m³)  \
0           35.04      40.31        41.44        11.57        1.32
1           33.60      39.88        43.22        10.98        1.26
2           35.11      41.15        41.41        11.58        1.28
3           33.86      39.27        43.20        10.27        1.25
4           33.36      39.21        41.54        10.26        1.26
...           ...        ...          ...          ...         ...
8779        62.81      57.15        45.63        14.83        1.66
8780        59.62      67.87        46.22        15.53        1.88
8781        56.93      73.58        47.91        15.62        2.05
8782        56.39      80.21        49.37        17.36        2.16
8783        49.38      84.32        48.89        17.65        2.15

      Ozone (µg/m³)  ...  MP-Xylene (µg/m³)  AT (°C)  RH (%)  WS (m/s)  \
0             12.89  ...               1.68    11.02   76.22      0.53
1             13.40  ...               2.00    10.96   76.29      0.52
2             13.17  ...               3.87    10.89   76.27      0.54
3             12.99  ...               4.02    10.84   76.16      0.52
4             12.85  ...               2.22    10.78   76.14      0.66
...             ...  ...                ...      ...     ...       ...
8779          14.38  ...               0.98    12.84   85.45      0.56
8780          12.03  ...               2.04    12.63   87.28      0.49
8781          11.81  ...               2.28    12.43   88.25      0.62
8782          12.11  ...               2.48    12.07   89.32      0.61
8783          11.07  ...               2.34    11.64   90.34      0.55

      WD (deg)  RF (mm)  TOT-RF (mm)  SR (W/mt2)  BP (mmHg)  VWS (m/s)
0       168.11      0.0          0.0        9.49     974.89       0.20
1       168.11      0.0          0.0        9.54     974.86       0.21
2       177.42      0.0          0.0        9.66     974.89       0.20
3       182.27      0.0          0.0        9.69     974.85       0.20
4       167.64      0.0          0.0        9.64     974.72       0.19
...        ...      ...          ...         ...        ...        ...
8779    165.44      0.0          0.0       10.49     977.48      -0.02
8780    171.28      0.0          0.0       10.67     977.80      -0.03
8781    175.76      0.0          0.0       10.79     977.83      -0.02
8782    153.84      0.0          0.0       10.84     977.67      -0.03
8783    160.78      0.0          0.0       11.01     977.40      -0.02

[8784 rows x 25 columns]>

In [49]:
df.isnull().sum()

Timestamp                 0
PM2.5 (µg/m³)             0
PM10 (µg/m³)              0
NO (µg/m³)                0
NO2 (µg/m³)               0
NOx (ppb)                 0
NH3 (µg/m³)               0
SO2 (µg/m³)               0
CO (mg/m³)                0
Ozone (µg/m³)             0
Benzene (µg/m³)           0
Toluene (µg/m³)           0
Xylene (µg/m³)            0
O Xylene (µg/m³)       8784
Eth-Benzene (µg/m³)       0
MP-Xylene (µg/m³)         0
AT (°C)                   0
RH (%)                    0
WS (m/s)                  0
WD (deg)                  0
RF (mm)                   0
TOT-RF (mm)               0
SR (W/mt2)                0
BP (mmHg)                 0
VWS (m/s)                 0
dtype: int64

In [50]:
#as the whole column is empty 
df.drop(columns=['O Xylene (µg/m³)'], inplace=True)

In [51]:
df.isnull().sum()

Timestamp              0
PM2.5 (µg/m³)          0
PM10 (µg/m³)           0
NO (µg/m³)             0
NO2 (µg/m³)            0
NOx (ppb)              0
NH3 (µg/m³)            0
SO2 (µg/m³)            0
CO (mg/m³)             0
Ozone (µg/m³)          0
Benzene (µg/m³)        0
Toluene (µg/m³)        0
Xylene (µg/m³)         0
Eth-Benzene (µg/m³)    0
MP-Xylene (µg/m³)      0
AT (°C)                0
RH (%)                 0
WS (m/s)               0
WD (deg)               0
RF (mm)                0
TOT-RF (mm)            0
SR (W/mt2)             0
BP (mmHg)              0
VWS (m/s)              0
dtype: int64

In [52]:
# #now we need to calculate the aqi (indian standard)
# AQI Range	Category
# 0–50	Good
# 51–100	Satisfactory
# 101–200	Moderate
# 201–300	Poor
# 301–400	Very Poor
# 401–500	Severe

In [53]:
def get_aqi_category_pm25(pm):
    if pm <= 30:
        return "Good"
    elif pm <= 60:
        return "Satisfactory"
    elif pm <= 90:
        return "Moderate"
    elif pm <= 120:
        return "Poor"
    elif pm <= 250:
        return "Very Poor"
    else:
        return "Severe"

In [54]:
df['AQI_Category'] = df['PM2.5 (µg/m³)'].apply(get_aqi_category_pm25)

In [55]:
df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    2448
Very Poor       2035
Moderate        1721
Good            1059
Poor             916
Severe           605
Name: count, dtype: int64

In [56]:
#fix the timestamp column 
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['Month'] = df['Timestamp'].dt.month
df['Hour'] = df['Timestamp'].dt.hour
df['Weekday'] = df['Timestamp'].dt.weekday

df.drop(columns=['Timestamp'], inplace=True)

In [57]:
df

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),AQI_Category,Month,Hour,Weekday
0,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,1.60,...,168.11,0.0,0.0,9.49,974.89,0.20,Very Poor,1,0,0
1,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,1.56,...,168.11,0.0,0.0,9.54,974.86,0.21,Very Poor,1,1,0
2,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,2.34,...,177.42,0.0,0.0,9.66,974.89,0.20,Very Poor,1,2,0
3,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,2.30,...,182.27,0.0,0.0,9.69,974.85,0.20,Very Poor,1,3,0
4,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,1.63,...,167.64,0.0,0.0,9.64,974.72,0.19,Very Poor,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,198.61,321.53,27.89,62.81,57.15,45.63,14.83,1.66,14.38,2.15,...,165.44,0.0,0.0,10.49,977.48,-0.02,Very Poor,12,19,1
8780,197.96,329.01,43.13,59.62,67.87,46.22,15.53,1.88,12.03,2.46,...,171.28,0.0,0.0,10.67,977.80,-0.03,Very Poor,12,20,1
8781,208.68,351.64,51.96,56.93,73.58,47.91,15.62,2.05,11.81,2.68,...,175.76,0.0,0.0,10.79,977.83,-0.02,Very Poor,12,21,1
8782,227.68,374.71,61.51,56.39,80.21,49.37,17.36,2.16,12.11,3.03,...,153.84,0.0,0.0,10.84,977.67,-0.03,Very Poor,12,22,1
8783,246.06,391.50,71.77,49.38,84.32,48.89,17.65,2.15,11.07,2.72,...,160.78,0.0,0.0,11.01,977.40,-0.02,Very Poor,12,23,1

In [58]:
df.describe()

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),Month,Hour,Weekday
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,...,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,104.202806,211.772991,28.373567,42.676815,48.231988,38.265427,14.909803,1.285791,34.143564,2.078389,...,0.984657,174.834636,0.024611,0.013977,108.925445,962.779421,-0.023903,6.513661,11.500000,2.986339
std,89.162133,127.221427,30.639896,18.234629,33.062084,7.957026,4.861207,0.635254,24.851439,1.192652,...,0.515051,21.090926,0.174214,0.097931,143.269424,6.432581,0.298122,3.451430,6.922581,2.003480
min,7.640000,11.850000,4.390000,15.680000,15.620000,23.710000,7.570000,0.520000,5.670000,0.460000,...,0.360000,109.230000,0.000000,0.000000,5.340000,943.510000,-1.870000,1.000000,0.000000,0.000000
25%,43.027500,115.455000,11.550000,28.040000,27.137500,32.050000,11.730000,0.870000,16.177500,1.190000,...,0.610000,158.137500,0.000000,0.000000,12.657500,959.560000,-0.090000,4.000000,5.750000,1.000000
50%,73.630000,185.890000,16.050000,37.900000,35.545000,36.850000,13.730000,1.070000,24.950000,1.760000,...,0.830000,177.135000,0.000000,0.000000,20.315000,962.730000,0.010000,7.000000,11.500000,3.000000
75%,140.355000,287.120000,30.055000,54.110000,56.462500,42.800000,16.640000,1.450000,43.007500,2.700000,...,1.230000,192.592500,0.000000,0.000000,176.335000,965.440000,0.100000,10.000000,17.250000,5.000000
max,820.080000,914.670000,207.060000,150.820000,226.450000,76.390000,68.670000,4.620000,126.210000,17.740000,...,5.790000,222.070000,6.870000,3.330000,645.720000,989.550000,0.690000,12.000000,23.000000,6.000000

In [59]:
df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    2448
Very Poor       2035
Moderate        1721
Good            1059
Poor             916
Severe           605
Name: count, dtype: int64

In [60]:
df

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),AQI_Category,Month,Hour,Weekday
0,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,1.60,...,168.11,0.0,0.0,9.49,974.89,0.20,Very Poor,1,0,0
1,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,1.56,...,168.11,0.0,0.0,9.54,974.86,0.21,Very Poor,1,1,0
2,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,2.34,...,177.42,0.0,0.0,9.66,974.89,0.20,Very Poor,1,2,0
3,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,2.30,...,182.27,0.0,0.0,9.69,974.85,0.20,Very Poor,1,3,0
4,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,1.63,...,167.64,0.0,0.0,9.64,974.72,0.19,Very Poor,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,198.61,321.53,27.89,62.81,57.15,45.63,14.83,1.66,14.38,2.15,...,165.44,0.0,0.0,10.49,977.48,-0.02,Very Poor,12,19,1
8780,197.96,329.01,43.13,59.62,67.87,46.22,15.53,1.88,12.03,2.46,...,171.28,0.0,0.0,10.67,977.80,-0.03,Very Poor,12,20,1
8781,208.68,351.64,51.96,56.93,73.58,47.91,15.62,2.05,11.81,2.68,...,175.76,0.0,0.0,10.79,977.83,-0.02,Very Poor,12,21,1
8782,227.68,374.71,61.51,56.39,80.21,49.37,17.36,2.16,12.11,3.03,...,153.84,0.0,0.0,10.84,977.67,-0.03,Very Poor,12,22,1
8783,246.06,391.50,71.77,49.38,84.32,48.89,17.65,2.15,11.07,2.72,...,160.78,0.0,0.0,11.01,977.40,-0.02,Very Poor,12,23,1

In [61]:
#creates aqi category to numeric 

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Create numeric target separately
y = le.fit_transform(df['AQI_Category'])

In [65]:
y

array([5, 5, 5, ..., 5, 5, 5], shape=(8784,))

In [62]:
df

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),AQI_Category,Month,Hour,Weekday
0,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,1.60,...,168.11,0.0,0.0,9.49,974.89,0.20,Very Poor,1,0,0
1,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,1.56,...,168.11,0.0,0.0,9.54,974.86,0.21,Very Poor,1,1,0
2,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,2.34,...,177.42,0.0,0.0,9.66,974.89,0.20,Very Poor,1,2,0
3,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,2.30,...,182.27,0.0,0.0,9.69,974.85,0.20,Very Poor,1,3,0
4,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,1.63,...,167.64,0.0,0.0,9.64,974.72,0.19,Very Poor,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,198.61,321.53,27.89,62.81,57.15,45.63,14.83,1.66,14.38,2.15,...,165.44,0.0,0.0,10.49,977.48,-0.02,Very Poor,12,19,1
8780,197.96,329.01,43.13,59.62,67.87,46.22,15.53,1.88,12.03,2.46,...,171.28,0.0,0.0,10.67,977.80,-0.03,Very Poor,12,20,1
8781,208.68,351.64,51.96,56.93,73.58,47.91,15.62,2.05,11.81,2.68,...,175.76,0.0,0.0,10.79,977.83,-0.02,Very Poor,12,21,1
8782,227.68,374.71,61.51,56.39,80.21,49.37,17.36,2.16,12.11,3.03,...,153.84,0.0,0.0,10.84,977.67,-0.03,Very Poor,12,22,1
8783,246.06,391.50,71.77,49.38,84.32,48.89,17.65,2.15,11.07,2.72,...,160.78,0.0,0.0,11.01,977.40,-0.02,Very Poor,12,23,1

In [63]:
X = df.drop(columns=['AQI_Category'])

In [64]:
X

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),Month,Hour,Weekday
0,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,1.60,...,0.53,168.11,0.0,0.0,9.49,974.89,0.20,1,0,0
1,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,1.56,...,0.52,168.11,0.0,0.0,9.54,974.86,0.21,1,1,0
2,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,2.34,...,0.54,177.42,0.0,0.0,9.66,974.89,0.20,1,2,0
3,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,2.30,...,0.52,182.27,0.0,0.0,9.69,974.85,0.20,1,3,0
4,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,1.63,...,0.66,167.64,0.0,0.0,9.64,974.72,0.19,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,198.61,321.53,27.89,62.81,57.15,45.63,14.83,1.66,14.38,2.15,...,0.56,165.44,0.0,0.0,10.49,977.48,-0.02,12,19,1
8780,197.96,329.01,43.13,59.62,67.87,46.22,15.53,1.88,12.03,2.46,...,0.49,171.28,0.0,0.0,10.67,977.80,-0.03,12,20,1
8781,208.68,351.64,51.96,56.93,73.58,47.91,15.62,2.05,11.81,2.68,...,0.62,175.76,0.0,0.0,10.79,977.83,-0.02,12,21,1
8782,227.68,374.71,61.51,56.39,80.21,49.37,17.36,2.16,12.11,3.03,...,0.61,153.84,0.0,0.0,10.84,977.67,-0.03,12,22,1
8783,246.06,391.50,71.77,49.38,84.32,48.89,17.65,2.15,11.07,2.72,...,0.55,160.78,0.0,0.0,11.01,977.40,-0.02,12,23,1

In [66]:
#apply standard scalling for standardization 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [67]:
X_scaled

array([[ 0.75818107,  0.46918517, -0.41234755, ..., -1.59759128,
        -1.66132477, -1.49066076],
       [ 0.73429065,  0.43231822, -0.39798637, ..., -1.59759128,
        -1.51686175, -1.49066076],
       [ 0.67619093,  0.35646189, -0.38590992, ..., -1.59759128,
        -1.37239873, -1.49066076],
       ...,
       [ 1.17183313,  1.0994608 ,  0.76983865, ...,  1.58967457,
         1.37239873, -0.9915008 ],
       [ 1.3849402 ,  1.2808085 ,  1.08154152, ...,  1.58967457,
         1.51686175, -0.9915008 ],
       [ 1.59109326,  1.41279064,  1.41641812, ...,  1.58967457,
         1.66132477, -0.9915008 ]], shape=(8784, 26))

In [68]:
#convert it back to dataframe 


X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df['AQI_Label'] = y

In [69]:
#final dataset check 
X_scaled_df.isnull().sum().sum()

np.int64(0)

In [70]:
X_scaled_df.shape

(8784, 27)

In [71]:
#saving the final dataset 
X_scaled_df.to_csv("air_quality_model_ready.csv", index=False)