In [29]:
#build classification model to predict AQI category (good,saterfactory, moderate, poor, very poor, severe)usng pollutant

In [30]:
import pandas as pd
import numpy as np

In [31]:
#load the datasets
poll_df = pd.read_csv("Dehradun_poll.csv")

In [32]:
#shape 
print("Pollutant Data Shape:", poll_df.shape)

Pollutant Data Shape: (8784, 25)

In [33]:
poll_df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,2024-01-01 00:00:00,122.60,134.92,0.24,5.31,5.56,NaN,1.02,2.09,0.03,...,NaN,9.65,99.00,0.49,234.66,NaN,NaN,2.14,806.49,NaN
1,2024-01-01 01:00:00,114.88,130.00,0.23,4.80,5.03,NaN,1.03,2.03,0.05,...,NaN,9.60,99.54,0.60,184.85,NaN,NaN,1.65,808.07,NaN
2,2024-01-01 02:00:00,111.74,122.87,0.16,4.56,4.72,NaN,0.99,1.96,0.02,...,NaN,9.54,99.64,0.49,220.11,NaN,NaN,1.60,809.83,NaN
3,2024-01-01 03:00:00,103.71,109.44,0.20,4.46,4.65,NaN,0.92,1.95,0.02,...,NaN,9.26,99.65,0.99,241.67,NaN,NaN,1.44,810.46,NaN
4,2024-01-01 04:00:00,91.02,97.88,0.16,4.24,4.40,NaN,0.88,1.82,0.06,...,NaN,8.94,99.66,0.98,236.00,NaN,NaN,1.24,811.53,NaN

In [34]:
poll_df.tail()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
8779,2024-12-31 19:00:00,139.17,174.07,0.16,4.00,4.12,NaN,0.92,1.59,8.94,...,NaN,11.99,92.26,0.49,187.11,NaN,NaN,0.82,800.32,NaN
8780,2024-12-31 20:00:00,134.52,169.50,0.14,3.16,3.30,NaN,0.84,1.52,10.25,...,NaN,11.45,93.01,1.44,260.87,NaN,NaN,0.78,800.32,NaN
8781,2024-12-31 21:00:00,105.32,130.52,0.07,2.33,2.38,NaN,0.97,1.41,13.70,...,NaN,11.30,91.28,1.55,263.65,NaN,NaN,0.83,800.32,NaN
8782,2024-12-31 22:00:00,86.73,103.80,0.07,2.49,2.54,NaN,0.83,1.41,14.16,...,NaN,11.22,89.69,1.28,257.02,NaN,NaN,0.83,800.32,NaN
8783,2024-12-31 23:00:00,86.91,101.86,0.08,2.18,2.20,NaN,0.95,1.38,14.09,...,NaN,11.06,90.02,0.84,245.31,NaN,NaN,0.81,800.32,NaN

In [36]:
#columns 
print("Pollutant Columns:", poll_df.columns)

Pollutant Columns: Index(['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)',
       'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='object')

In [39]:
print(poll_df.columns)

Index(['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)',
       'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='object')

In [37]:
#data types
print(poll_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            8784 non-null   object
 1   PM2.5 (µg/m³)        8280 non-null   float64
 2   PM10 (µg/m³)         8326 non-null   float64
 3   NO (µg/m³)           8554 non-null   float64
 4   NO2 (µg/m³)          8462 non-null   float64
 5   NOx (ppb)            8594 non-null   float64
 6   NH3 (µg/m³)          0 non-null      float64
 7   SO2 (µg/m³)          8557 non-null   float64
 8   CO (mg/m³)           8596 non-null   float64
 9   Ozone (µg/m³)        8488 non-null   float64
 10  Benzene (µg/m³)      0 non-null      float64
 11  Toluene (µg/m³)      0 non-null      float64
 12  Xylene (µg/m³)       0 non-null      float64
 13  O Xylene (µg/m³)     0 non-null      float64
 14  Eth-Benzene (µg/m³)  0 non-null      float64
 15  MP-Xylene (µg/m³)    0 non-null      float64
 16  AT (°C)              8561 non-null   float64
 17  RH (%)               8561 non-null   float64
 18  WS (m/s)             8561 non-null   float64
 19  WD (deg)             8561 non-null   float64
 20  RF (mm)              0 non-null      float64
 21  TOT-RF (mm)          0 non-null      float64
 22  SR (W/mt2)           8596 non-null   float64
 23  BP (mmHg)            8561 non-null   float64
 24  VWS (m/s)            0 non-null      float64
dtypes: float64(24), object(1)
memory usage: 1.7+ MB
None

In [38]:
#missing values 
poll_df.isnull().sum()

Timestamp                 0
PM2.5 (µg/m³)           504
PM10 (µg/m³)            458
NO (µg/m³)              230
NO2 (µg/m³)             322
NOx (ppb)               190
NH3 (µg/m³)            8784
SO2 (µg/m³)             227
CO (mg/m³)              188
Ozone (µg/m³)           296
Benzene (µg/m³)        8784
Toluene (µg/m³)        8784
Xylene (µg/m³)         8784
O Xylene (µg/m³)       8784
Eth-Benzene (µg/m³)    8784
MP-Xylene (µg/m³)      8784
AT (°C)                 223
RH (%)                  223
WS (m/s)                223
WD (deg)                223
RF (mm)                8784
TOT-RF (mm)            8784
SR (W/mt2)              188
BP (mmHg)               223
VWS (m/s)              8784
dtype: int64

In [40]:
#clean column names 
poll_df.columns = poll_df.columns.str.replace(' ', '_')
poll_df.columns = poll_df.columns.str.replace('(', '')
poll_df.columns = poll_df.columns.str.replace(')', '')
poll_df.columns = poll_df.columns.str.replace('/', '')
poll_df.columns = poll_df.columns.str.replace('µg/m³', 'ugm3')
poll_df.columns = poll_df.columns.str.replace('°C', 'C')
poll_df.columns = poll_df.columns.str.replace('%', 'percent')
poll_df.columns = poll_df.columns.str.replace('-', '_')

print(poll_df.columns)

Index(['Timestamp', 'PM2.5_µgm³', 'PM10_µgm³', 'NO_µgm³', 'NO2_µgm³',
       'NOx_ppb', 'NH3_µgm³', 'SO2_µgm³', 'CO_mgm³', 'Ozone_µgm³',
       'Benzene_µgm³', 'Toluene_µgm³', 'Xylene_µgm³', 'O_Xylene_µgm³',
       'Eth_Benzene_µgm³', 'MP_Xylene_µgm³', 'AT_C', 'RH_percent', 'WS_ms',
       'WD_deg', 'RF_mm', 'TOT_RF_mm', 'SR_Wmt2', 'BP_mmHg', 'VWS_ms'],
      dtype='object')

In [41]:
#now we have to convert the timestamp column to datetime format 
poll_df['Timestamp'] = pd.to_datetime(poll_df['Timestamp'])
poll_df['Timestamp'].head()

0   2024-01-01 00:00:00
1   2024-01-01 01:00:00
2   2024-01-01 02:00:00
3   2024-01-01 03:00:00
4   2024-01-01 04:00:00
Name: Timestamp, dtype: datetime64[ns]

In [42]:
#in our dataset there is no AQI column so we have to calculate teh aqi then make a category for aqi 
# Indian AQI standard:

# 0–50 → Good

# 51–100 → Satisfactory

# 101–200 → Moderate

# 201–300 → Poor

# 301–400 → Very Poor

# 401+ → Severe

# We’ll apply this on PM2.5.

In [45]:
poll_df.shape

(8784, 25)

In [50]:
#since we have hourly data we have to convert it to daily average bcox aqi is calculated like that

#first the timestamp data in date column
poll_df['Date'] = poll_df['Timestamp'].dt.date

#now we have to group by date and then we will take the daily average
daily_df = poll_df.groupby('Date').mean(numeric_only=True).reset_index()

#now convert date back to date time 
daily_df['Date'] = pd.to_datetime(daily_df['Date'])

daily_df.shape

(366, 25)

In [51]:
daily_df.head()

#from this we have get that we have 25 features, daily averaged data, date column, pollutants and weather , many nan values

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,NH3_µgm³,SO2_µgm³,CO_mgm³,Ozone_µgm³,...,MP_Xylene_µgm³,AT_C,RH_percent,WS_ms,WD_deg,RF_mm,TOT_RF_mm,SR_Wmt2,BP_mmHg,VWS_ms
0,2024-01-01,86.593333,111.744167,0.399167,3.477917,3.877083,NaN,0.920417,1.750833,1.924167,...,NaN,11.950000,89.532500,0.998750,209.258333,NaN,NaN,78.118333,804.940417,NaN
1,2024-01-02,81.960000,107.050000,0.289167,3.101667,3.360000,NaN,0.900833,1.607917,1.986667,...,NaN,11.753750,87.733333,0.875000,192.387917,NaN,NaN,80.608750,810.004167,NaN
2,2024-01-03,58.179130,84.600870,0.337083,2.002500,2.340833,NaN,0.873333,1.400000,2.646250,...,NaN,11.776667,80.602917,0.886250,191.248750,NaN,NaN,91.888333,801.435417,NaN
3,2024-01-04,66.098333,100.725417,0.227500,2.452917,2.679167,NaN,0.811667,1.359167,3.660000,...,NaN,11.838333,79.734167,0.830000,199.377500,NaN,NaN,88.194167,800.700000,NaN
4,2024-01-05,80.360833,119.424167,0.443333,2.785000,3.230417,NaN,0.857083,1.434583,4.252500,...,NaN,11.786667,79.610000,0.939167,193.410833,NaN,NaN,87.461667,800.397917,NaN

In [53]:
#next step is to clean the daily dataset propely as ther are nan values

#check missing value percentage if a coulumn have 70% missing value we will droop that column

miss_percentage = daily_df.isnull().mean() * 100
miss_percentage.sort_values(ascending = False)

NH3_µgm³            100.0
RF_mm               100.0
TOT_RF_mm           100.0
Eth_Benzene_µgm³    100.0
MP_Xylene_µgm³      100.0
O_Xylene_µgm³       100.0
Xylene_µgm³         100.0
Toluene_µgm³        100.0
Benzene_µgm³        100.0
VWS_ms              100.0
SO2_µgm³              0.0
NOx_ppb               0.0
NO2_µgm³              0.0
PM10_µgm³             0.0
NO_µgm³               0.0
PM2.5_µgm³            0.0
Date                  0.0
CO_mgm³               0.0
Ozone_µgm³            0.0
AT_C                  0.0
RH_percent            0.0
WD_deg                0.0
WS_ms                 0.0
SR_Wmt2               0.0
BP_mmHg               0.0
dtype: float64

In [54]:
#therer are many columns with 100 % missing now we will drop them 

cols_to_drop = [
    'NH3_µgm³',
    'RF_mm',
    'TOT_RF_mm',
    'Eth_Benzene_µgm³',
    'MP_Xylene_µgm³',
    'O_Xylene_µgm³',
    'Xylene_µgm³',
    'Toluene_µgm³',
    'Benzene_µgm³',
    'VWS_ms'
]

daily_df = daily_df.drop(columns=cols_to_drop)

daily_df.shape

(366, 15)

In [55]:
daily_df.head()

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg
0,2024-01-01,86.593333,111.744167,0.399167,3.477917,3.877083,0.920417,1.750833,1.924167,11.950000,89.532500,0.998750,209.258333,78.118333,804.940417
1,2024-01-02,81.960000,107.050000,0.289167,3.101667,3.360000,0.900833,1.607917,1.986667,11.753750,87.733333,0.875000,192.387917,80.608750,810.004167
2,2024-01-03,58.179130,84.600870,0.337083,2.002500,2.340833,0.873333,1.400000,2.646250,11.776667,80.602917,0.886250,191.248750,91.888333,801.435417
3,2024-01-04,66.098333,100.725417,0.227500,2.452917,2.679167,0.811667,1.359167,3.660000,11.838333,79.734167,0.830000,199.377500,88.194167,800.700000
4,2024-01-05,80.360833,119.424167,0.443333,2.785000,3.230417,0.857083,1.434583,4.252500,11.786667,79.610000,0.939167,193.410833,87.461667,800.397917

In [57]:
#now we will make a aqi category we have set  a range for each category according to indian aqi category 

def categorize_aqi(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Satisfactory"
    elif pm25 <= 200:
        return "Moderate"
    elif pm25 <= 300:
        return "Poor"
    elif pm25 <= 400:
        return "Very Poor"
    else:
        return "Severe"

daily_df['AQI_Category'] = daily_df['PM2.5_µgm³'].apply(categorize_aqi)

#now we have make a aqi category lets check what values are given 

daily_df[['PM2.5_µgm³', 'AQI_Category']].head()

   PM2.5_µgm³  AQI_Category
0   86.593333  Satisfactory
1   81.960000  Satisfactory
2   58.179130  Satisfactory
3   66.098333  Satisfactory
4   80.360833  Satisfactory

In [58]:
#now lets check how many days 
daily_df['AQI_Category'].value_counts()

AQI_Category
Good            240
Satisfactory     95
Moderate         31
Name: count, dtype: int64

In [60]:

daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          366 non-null    datetime64[ns]
 1   PM2.5_µgm³    366 non-null    float64
 2   PM10_µgm³     366 non-null    float64
 3   NO_µgm³       366 non-null    float64
 4   NO2_µgm³      366 non-null    float64
 5   NOx_ppb       366 non-null    float64
 6   SO2_µgm³      366 non-null    float64
 7   CO_mgm³       366 non-null    float64
 8   Ozone_µgm³    366 non-null    float64
 9   AT_C          366 non-null    float64
 10  RH_percent    366 non-null    float64
 11  WS_ms         366 non-null    float64
 12  WD_deg        366 non-null    float64
 13  SR_Wmt2       366 non-null    float64
 14  BP_mmHg       366 non-null    float64
 15  AQI_Category  366 non-null    object
dtypes: datetime64[ns](1), float64(14), object(1)
memory usage: 45.9+ KB