In [23]:
import joblib
import pandas as pd

In [24]:
model = joblib.load("svm_model.pkl")
scaler = joblib.load("scaler.pkl")
le = joblib.load("label_encoder.pkl")

In [25]:
df = pd.read_csv("final_data.csv")
X = df.drop(columns=['AQI_Label'])

In [26]:
df

,PM2.5 (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),Toluene (µg/m³),Xylene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Month,AQI_Label
0,0.758181,-0.418832,-0.239623,0.398988,-0.687071,0.053854,-0.855273,-0.401137,-1.346117,-2.110376,...,-0.294984,-1.790803,0.773675,-0.882793,-0.318858,-0.694085,1.882801,0.751086,-1.597591,5
1,0.734291,-0.497807,-0.252630,0.622702,-0.808447,-0.040602,-0.834750,-0.434677,-1.348278,-2.135281,...,-0.168583,-1.797989,0.777419,-0.902209,-0.318858,-0.693736,1.878137,0.784631,-1.597591,5
2,0.676191,-0.414993,-0.214215,0.395217,-0.685014,-0.009117,-0.844006,0.219365,-1.328828,-2.143583,...,0.570072,-1.806374,0.776349,-0.863376,0.122589,-0.692898,1.882801,0.751086,-1.597591,5
3,0.648375,-0.483548,-0.271081,0.620188,-0.954509,-0.056345,-0.851249,0.185824,-1.343956,-2.019058,...,0.629322,-1.812362,0.770466,-0.902209,0.352559,-0.692689,1.876582,0.751086,-1.597591,5
4,0.618428,-0.510970,-0.272896,0.411556,-0.956566,-0.040602,-0.856883,-0.375981,-1.393662,-1.990002,...,-0.081683,-1.819549,0.769396,-0.630376,-0.341144,-0.693038,1.856371,0.717541,-1.597591,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,1.058886,1.104181,0.269751,0.925596,-0.016417,0.589103,-0.795314,0.060047,-0.224506,0.093719,...,-0.571486,-1.572812,1.267328,-0.824543,-0.445460,-0.687104,2.285461,0.013091,1.589675,5
8780,1.051596,0.929229,0.594008,0.999749,0.127588,0.935441,-0.889881,0.319987,0.046712,0.114473,...,-0.152783,-1.597965,1.365203,-0.960459,-0.168548,-0.685848,2.335211,-0.020454,1.589675,5
8781,1.171833,0.781699,0.766723,1.212152,0.146103,1.203065,-0.898734,0.504460,-0.061343,0.118624,...,-0.057983,-1.621920,1.417082,-0.708043,0.043877,-0.685010,2.339875,0.013091,1.589675,5
8782,1.384940,0.752084,0.967266,1.395648,0.504059,1.376234,-0.886662,0.797940,0.019698,0.118624,...,0.021018,-1.665039,1.474309,-0.727460,-0.995491,-0.684661,2.315000,-0.020454,1.589675,5
8783,1.591093,0.367628,1.091585,1.335320,0.563719,1.360492,-0.928513,0.538001,0.132075,0.110322,...,-0.034283,-1.716542,1.528862,-0.843960,-0.666421,-0.683475,2.273024,0.013091,1.589675,5

In [27]:
X

,PM2.5 (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),Toluene (µg/m³),Xylene (µg/m³),Eth-Benzene (µg/m³),MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Month
0,0.758181,-0.418832,-0.239623,0.398988,-0.687071,0.053854,-0.855273,-0.401137,-1.346117,-2.110376,0.667172,-0.294984,-1.790803,0.773675,-0.882793,-0.318858,-0.694085,1.882801,0.751086,-1.597591
1,0.734291,-0.497807,-0.252630,0.622702,-0.808447,-0.040602,-0.834750,-0.434677,-1.348278,-2.135281,0.667172,-0.168583,-1.797989,0.777419,-0.902209,-0.318858,-0.693736,1.878137,0.784631,-1.597591
2,0.676191,-0.414993,-0.214215,0.395217,-0.685014,-0.009117,-0.844006,0.219365,-1.328828,-2.143583,1.956269,0.570072,-1.806374,0.776349,-0.863376,0.122589,-0.692898,1.882801,0.751086,-1.597591
3,0.648375,-0.483548,-0.271081,0.620188,-0.954509,-0.056345,-0.851249,0.185824,-1.343956,-2.019058,2.105260,0.629322,-1.812362,0.770466,-0.902209,0.352559,-0.692689,1.876582,0.751086,-1.597591
4,0.618428,-0.510970,-0.272896,0.411556,-0.956566,-0.040602,-0.856883,-0.375981,-1.393662,-1.990002,0.291456,-0.081683,-1.819549,0.769396,-0.630376,-0.341144,-0.693038,1.856371,0.717541,-1.597591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,1.058886,1.104181,0.269751,0.925596,-0.016417,0.589103,-0.795314,0.060047,-0.224506,0.093719,-0.712615,-0.571486,-1.572812,1.267328,-0.824543,-0.445460,-0.687104,2.285461,0.013091,1.589675
8780,1.051596,0.929229,0.594008,0.999749,0.127588,0.935441,-0.889881,0.319987,0.046712,0.114473,0.369190,-0.152783,-1.597965,1.365203,-0.960459,-0.168548,-0.685848,2.335211,-0.020454,1.589675
8781,1.171833,0.781699,0.766723,1.212152,0.146103,1.203065,-0.898734,0.504460,-0.061343,0.118624,0.557048,-0.057983,-1.621920,1.417082,-0.708043,0.043877,-0.685010,2.339875,0.013091,1.589675
8782,1.384940,0.752084,0.967266,1.395648,0.504059,1.376234,-0.886662,0.797940,0.019698,0.118624,0.427491,0.021018,-1.665039,1.474309,-0.727460,-0.995491,-0.684661,2.315000,-0.020454,1.589675
8783,1.591093,0.367628,1.091585,1.335320,0.563719,1.360492,-0.928513,0.538001,0.132075,0.110322,0.310889,-0.034283,-1.716542,1.528862,-0.843960,-0.666421,-0.683475,2.273024,0.013091,1.589675

In [28]:
pred = model.predict(X.iloc[[0]])

print("Predicted Label:", pred[0])
print("Predicted Category:", le.inverse_transform(pred)[0])

Predicted Label: 5
Predicted Category: Very Poor

In [29]:
row = 100

pred = model.predict(X.iloc[[row]])

print("Sample Row:", row)
print("Predicted Label:", pred[0])
print("Predicted Category:", le.inverse_transform(pred)[0])
print("Actual Label:", df['AQI_Label'].iloc[row])

Sample Row: 100
Predicted Label: 5
Predicted Category: Very Poor
Actual Label: 5

In [30]:
for i in range(5):
    pred = model.predict(X.iloc[[i]])
    print(i, le.inverse_transform(pred)[0])

0 Very Poor
1 Very Poor
2 Very Poor
3 Very Poor
4 Very Poor

In [31]:
row = int(input("Enter row number (0 to 8783): "))

pred = model.predict(X.iloc[[row]])

print("Predicted AQI:", le.inverse_transform(pred)[0])
print("Actual AQI Label:", le.inverse_transform([df['AQI_Label'].iloc[row]])[0])

Enter row number (0 to 8783):  7777

Predicted AQI: Severe
Actual AQI Label: Severe