In [1]:
#build classification model to predict AQI category (good,saterfactory, moderate, poor, very poor, severe)usng pollutant

In [2]:
import pandas as pd
import numpy as np

In [3]:
#load the datasets
poll_df = pd.read_csv("data.csv")

In [4]:
#shape 
print("Pollutant Data Shape:", poll_df.shape)

Pollutant Data Shape: (8784, 25)

In [5]:
poll_df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,2024-01-01 00:00:00,171.80,271.46,15.74,35.04,40.31,41.44,11.57,1.32,12.89,...,1.68,11.02,76.22,0.53,168.11,0.0,0.0,9.49,974.89,0.20
1,2024-01-01 01:00:00,169.67,266.77,16.18,33.60,39.88,43.22,10.98,1.26,13.40,...,2.00,10.96,76.29,0.52,168.11,0.0,0.0,9.54,974.86,0.21
2,2024-01-01 02:00:00,164.49,257.12,16.55,35.11,41.15,41.41,11.58,1.28,13.17,...,3.87,10.89,76.27,0.54,177.42,0.0,0.0,9.66,974.89,0.20
3,2024-01-01 03:00:00,162.01,252.37,15.37,33.86,39.27,43.20,10.27,1.25,12.99,...,4.02,10.84,76.16,0.52,182.27,0.0,0.0,9.69,974.85,0.20
4,2024-01-01 04:00:00,159.34,252.60,15.66,33.36,39.21,41.54,10.26,1.26,12.85,...,2.22,10.78,76.14,0.66,167.64,0.0,0.0,9.64,974.72,0.19

In [6]:
poll_df.tail()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
8779,2024-12-31 19:00:00,198.61,321.53,27.89,62.81,57.15,45.63,14.83,1.66,14.38,...,0.98,12.84,85.45,0.56,165.44,0.0,0.0,10.49,977.48,-0.02
8780,2024-12-31 20:00:00,197.96,329.01,43.13,59.62,67.87,46.22,15.53,1.88,12.03,...,2.04,12.63,87.28,0.49,171.28,0.0,0.0,10.67,977.80,-0.03
8781,2024-12-31 21:00:00,208.68,351.64,51.96,56.93,73.58,47.91,15.62,2.05,11.81,...,2.28,12.43,88.25,0.62,175.76,0.0,0.0,10.79,977.83,-0.02
8782,2024-12-31 22:00:00,227.68,374.71,61.51,56.39,80.21,49.37,17.36,2.16,12.11,...,2.48,12.07,89.32,0.61,153.84,0.0,0.0,10.84,977.67,-0.03
8783,2024-12-31 23:00:00,246.06,391.50,71.77,49.38,84.32,48.89,17.65,2.15,11.07,...,2.34,11.64,90.34,0.55,160.78,0.0,0.0,11.01,977.40,-0.02

In [7]:
#columns 
print("Pollutant Columns:", poll_df.columns)

Pollutant Columns: Index(['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)',
       'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='object')

In [8]:
print(poll_df.columns)

Index(['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)',
       'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='object')

In [9]:
#data types
print(poll_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            8784 non-null   object
 1   PM2.5 (µg/m³)        8784 non-null   float64
 2   PM10 (µg/m³)         8784 non-null   float64
 3   NO (µg/m³)           8784 non-null   float64
 4   NO2 (µg/m³)          8784 non-null   float64
 5   NOx (ppb)            8784 non-null   float64
 6   NH3 (µg/m³)          8784 non-null   float64
 7   SO2 (µg/m³)          8784 non-null   float64
 8   CO (mg/m³)           8784 non-null   float64
 9   Ozone (µg/m³)        8784 non-null   float64
 10  Benzene (µg/m³)      8784 non-null   float64
 11  Toluene (µg/m³)      8784 non-null   float64
 12  Xylene (µg/m³)       8784 non-null   float64
 13  O Xylene (µg/m³)     0 non-null      float64
 14  Eth-Benzene (µg/m³)  8784 non-null   float64
 15  MP-Xylene (µg/m³)    8784 non-null   float64
 16  AT (°C)              8784 non-null   float64
 17  RH (%)               8784 non-null   float64
 18  WS (m/s)             8784 non-null   float64
 19  WD (deg)             8784 non-null   float64
 20  RF (mm)              8784 non-null   float64
 21  TOT-RF (mm)          8784 non-null   float64
 22  SR (W/mt2)           8784 non-null   float64
 23  BP (mmHg)            8784 non-null   float64
 24  VWS (m/s)            8784 non-null   float64
dtypes: float64(24), object(1)
memory usage: 1.7+ MB
None

In [10]:
#missing values 
poll_df.isnull().sum()

Timestamp                 0
PM2.5 (µg/m³)             0
PM10 (µg/m³)              0
NO (µg/m³)                0
NO2 (µg/m³)               0
NOx (ppb)                 0
NH3 (µg/m³)               0
SO2 (µg/m³)               0
CO (mg/m³)                0
Ozone (µg/m³)             0
Benzene (µg/m³)           0
Toluene (µg/m³)           0
Xylene (µg/m³)            0
O Xylene (µg/m³)       8784
Eth-Benzene (µg/m³)       0
MP-Xylene (µg/m³)         0
AT (°C)                   0
RH (%)                    0
WS (m/s)                  0
WD (deg)                  0
RF (mm)                   0
TOT-RF (mm)               0
SR (W/mt2)                0
BP (mmHg)                 0
VWS (m/s)                 0
dtype: int64

In [11]:
#clean column names 
poll_df.columns = poll_df.columns.str.replace(' ', '_')
poll_df.columns = poll_df.columns.str.replace('(', '')
poll_df.columns = poll_df.columns.str.replace(')', '')
poll_df.columns = poll_df.columns.str.replace('/', '')
poll_df.columns = poll_df.columns.str.replace('µg/m³', 'ugm3')
poll_df.columns = poll_df.columns.str.replace('°C', 'C')
poll_df.columns = poll_df.columns.str.replace('%', 'percent')
poll_df.columns = poll_df.columns.str.replace('-', '_')

print(poll_df.columns)

Index(['Timestamp', 'PM2.5_µgm³', 'PM10_µgm³', 'NO_µgm³', 'NO2_µgm³',
       'NOx_ppb', 'NH3_µgm³', 'SO2_µgm³', 'CO_mgm³', 'Ozone_µgm³',
       'Benzene_µgm³', 'Toluene_µgm³', 'Xylene_µgm³', 'O_Xylene_µgm³',
       'Eth_Benzene_µgm³', 'MP_Xylene_µgm³', 'AT_C', 'RH_percent', 'WS_ms',
       'WD_deg', 'RF_mm', 'TOT_RF_mm', 'SR_Wmt2', 'BP_mmHg', 'VWS_ms'],
      dtype='object')

In [12]:
#now we have to convert the timestamp column to datetime format 
poll_df['Timestamp'] = pd.to_datetime(poll_df['Timestamp'])
poll_df['Timestamp'].head()

0   2024-01-01 00:00:00
1   2024-01-01 01:00:00
2   2024-01-01 02:00:00
3   2024-01-01 03:00:00
4   2024-01-01 04:00:00
Name: Timestamp, dtype: datetime64[ns]

In [13]:
#in our dataset there is no AQI column so we have to calculate teh aqi then make a category for aqi 
# Indian AQI standard:

# 0–50 → Good

# 51–100 → Satisfactory

# 101–200 → Moderate

# 201–300 → Poor

# 301–400 → Very Poor

# 401+ → Severe

# We’ll apply this on PM2.5.

In [14]:
poll_df.shape

(8784, 25)

In [15]:
#since we have hourly data we have to convert it to daily average bcox aqi is calculated like that

#first the timestamp data in date column
poll_df['Date'] = poll_df['Timestamp'].dt.date

#now we have to group by date and then we will take the daily average
daily_df = poll_df.groupby('Date').mean(numeric_only=True).reset_index()

#now convert date back to date time 
daily_df['Date'] = pd.to_datetime(daily_df['Date'])

daily_df.shape

(366, 25)

In [16]:
daily_df.head()

#from this we have get that we have 25 features, daily averaged data, date column, pollutants and weather , many nan values

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,NH3_µgm³,SO2_µgm³,CO_mgm³,Ozone_µgm³,...,MP_Xylene_µgm³,AT_C,RH_percent,WS_ms,WD_deg,RF_mm,TOT_RF_mm,SR_Wmt2,BP_mmHg,VWS_ms
0,2024-01-01,176.679583,293.727083,16.357500,33.182917,39.324583,39.693333,10.389583,1.177917,15.869583,...,2.756667,11.346250,72.005000,0.710833,174.558750,0.0,0.0,49.583750,974.870833,0.224583
1,2024-01-02,180.665000,293.752500,20.056250,35.415000,44.370417,38.382917,11.555417,1.162917,17.450000,...,2.709583,10.869583,69.444583,0.677500,169.500000,0.0,0.0,62.596250,974.491667,0.345833
2,2024-01-03,191.461250,306.088333,25.389583,38.743750,50.359167,43.125417,9.502083,1.485000,15.040833,...,2.426250,10.237083,79.782500,0.655000,167.399583,0.0,0.0,46.275417,974.446667,0.356250
3,2024-01-04,215.310417,347.739583,28.622917,39.125417,50.938333,41.807500,10.648333,1.319583,11.795417,...,2.192083,10.414167,80.744167,0.767917,200.645000,0.0,0.0,34.486667,974.443750,0.364167
4,2024-01-05,159.162500,275.042500,24.269583,39.634583,46.040833,44.304167,11.218750,1.270833,14.331250,...,2.157500,11.354583,81.830833,0.698333,189.891667,0.0,0.0,27.805833,974.436250,0.310417

In [17]:
#next step is to clean the daily dataset propely as ther are nan values

#check missing value percentage if a coulumn have 70% missing value we will droop that column

miss_percentage = daily_df.isnull().mean() * 100
miss_percentage.sort_values(ascending = False)

O_Xylene_µgm³       100.0
PM2.5_µgm³            0.0
PM10_µgm³             0.0
NO_µgm³               0.0
NO2_µgm³              0.0
NOx_ppb               0.0
NH3_µgm³              0.0
SO2_µgm³              0.0
Date                  0.0
CO_mgm³               0.0
Ozone_µgm³            0.0
Toluene_µgm³          0.0
Benzene_µgm³          0.0
Xylene_µgm³           0.0
Eth_Benzene_µgm³      0.0
MP_Xylene_µgm³        0.0
AT_C                  0.0
RH_percent            0.0
WS_ms                 0.0
WD_deg                0.0
RF_mm                 0.0
TOT_RF_mm             0.0
SR_Wmt2               0.0
BP_mmHg               0.0
VWS_ms                0.0
dtype: float64

In [18]:
#therer are many columns with 100 % missing now we will drop them 

cols_to_drop = [
    'NH3_µgm³',
    'RF_mm',
    'TOT_RF_mm',
    'Eth_Benzene_µgm³',
    'MP_Xylene_µgm³',
    'O_Xylene_µgm³',
    'Xylene_µgm³',
    'Toluene_µgm³',
    'Benzene_µgm³',
    'VWS_ms'
]

daily_df = daily_df.drop(columns=cols_to_drop)

daily_df.shape

(366, 15)

In [19]:
daily_df.head()

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg
0,2024-01-01,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833
1,2024-01-02,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667
2,2024-01-03,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667
3,2024-01-04,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750
4,2024-01-05,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250

In [20]:
#now we will make a aqi category we have set  a range for each category according to indian aqi category 

def categorize_aqi(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Satisfactory"
    elif pm25 <= 200:
        return "Moderate"
    elif pm25 <= 300:
        return "Poor"
    elif pm25 <= 400:
        return "Very Poor"
    else:
        return "Severe"

daily_df['AQI_Category'] = daily_df['PM2.5_µgm³'].apply(categorize_aqi)

#now we have make a aqi category lets check what values are given 

daily_df[['PM2.5_µgm³', 'AQI_Category']].head()

   PM2.5_µgm³ AQI_Category
0  176.679583     Moderate
1  180.665000     Moderate
2  191.461250     Moderate
3  215.310417         Poor
4  159.162500     Moderate

In [21]:
#now lets check how many days 
daily_df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    143
Good             97
Moderate         80
Poor             36
Very Poor         7
Severe            3
Name: count, dtype: int64

In [22]:

daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          366 non-null    datetime64[ns]
 1   PM2.5_µgm³    366 non-null    float64
 2   PM10_µgm³     366 non-null    float64
 3   NO_µgm³       366 non-null    float64
 4   NO2_µgm³      366 non-null    float64
 5   NOx_ppb       366 non-null    float64
 6   SO2_µgm³      366 non-null    float64
 7   CO_mgm³       366 non-null    float64
 8   Ozone_µgm³    366 non-null    float64
 9   AT_C          366 non-null    float64
 10  RH_percent    366 non-null    float64
 11  WS_ms         366 non-null    float64
 12  WD_deg        366 non-null    float64
 13  SR_Wmt2       366 non-null    float64
 14  BP_mmHg       366 non-null    float64
 15  AQI_Category  366 non-null    object
dtypes: datetime64[ns](1), float64(14), object(1)
memory usage: 45.9+ KB

In [23]:
#so now i am uploading this to github

In [24]:
#finalaizing clean dataset 
daily_df.isnull().sum()

Date            0
PM2.5_µgm³      0
PM10_µgm³       0
NO_µgm³         0
NO2_µgm³        0
NOx_ppb         0
SO2_µgm³        0
CO_mgm³         0
Ozone_µgm³      0
AT_C            0
RH_percent      0
WS_ms           0
WD_deg          0
SR_Wmt2         0
BP_mmHg         0
AQI_Category    0
dtype: int64

In [25]:
daily_df.dtypes

Date            datetime64[ns]
PM2.5_µgm³             float64
PM10_µgm³              float64
NO_µgm³                float64
NO2_µgm³               float64
NOx_ppb                float64
SO2_µgm³               float64
CO_mgm³                float64
Ozone_µgm³             float64
AT_C                   float64
RH_percent             float64
WS_ms                  float64
WD_deg                 float64
SR_Wmt2                float64
BP_mmHg                float64
AQI_Category            object
dtype: object

In [26]:
# #our dataset is lacking 
# #Right now:

# Good → 97

# Satisfactory → 143

# Moderate → 80

# Poor → 36

# Very Poor → 7

# Severe → 3

#there is very less data for severe, very poor

In [27]:
feature_cols = daily_df.drop(columns=['Date', 'AQI_Category']).columns

In [28]:
#so now we are creating synthetic samples
minor_classes = ['Poor', 'Very Poor', 'Severe']

stats = {}

for cls in minor_classes:
    cls_data = daily_df[daily_df['AQI_Category'] == cls]
    stats[cls] = {
        'mean': cls_data[feature_cols].mean(),
        'std': cls_data[feature_cols].std()
    }

In [29]:
#creating samples 
import numpy as np
import pandas as pd

def generate_samples(class_name, n_samples):
    mean = stats[class_name]['mean']
    std = stats[class_name]['std']
    
    synthetic = pd.DataFrame()
    
    for col in feature_cols:
        synthetic[col] = np.random.normal(mean[col], std[col], n_samples)
    
    synthetic['AQI_Category'] = class_name
    return synthetic

In [30]:
new_poor = generate_samples('Poor', 24)
new_vpoor = generate_samples('Very Poor', 53)
new_severe = generate_samples('Severe', 57)

In [31]:
#combining this with dataset 
synthetic_df = pd.concat(
    [daily_df, new_poor, new_vpoor, new_severe],
    ignore_index=True
)

synthetic_df

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
0,2024-01-01,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833,Moderate
1,2024-01-02,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667,Moderate
2,2024-01-03,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667,Moderate
3,2024-01-04,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750,Poor
4,2024-01-05,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,NaT,586.498152,659.311335,31.729843,51.059285,55.499271,15.255194,2.214521,29.760681,24.732187,78.404778,0.680237,190.634243,57.968577,963.701254,Severe
496,NaT,571.988300,629.313349,33.971877,49.545926,35.255735,14.617839,2.385924,28.363629,24.204462,77.529325,0.705796,194.679159,61.140436,962.810901,Severe
497,NaT,410.904046,702.229274,3.845862,52.024544,52.074945,13.998989,2.703408,32.956792,24.919254,81.849385,0.656507,197.854424,61.420218,963.033710,Severe
498,NaT,510.148393,551.481660,20.848115,48.293973,46.547960,15.489362,2.513495,30.787819,25.223937,75.096419,0.661409,203.286168,60.163099,961.946576,Severe
499,NaT,450.007278,587.518264,50.357062,45.877055,42.624375,15.158260,2.400524,32.747568,24.336505,74.161154,0.667413,194.443312,62.504044,963.599918,Severe

In [32]:
#remove negative values 
for col in feature_cols:
    synthetic_df[col] = synthetic_df[col].clip(lower=0)

In [33]:
synthetic_df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    143
Good             97
Moderate         80
Poor             60
Very Poor        60
Severe           60
Name: count, dtype: int64

In [34]:
synthetic_df

,Date,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
0,2024-01-01,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833,Moderate
1,2024-01-02,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667,Moderate
2,2024-01-03,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667,Moderate
3,2024-01-04,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750,Poor
4,2024-01-05,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,NaT,586.498152,659.311335,31.729843,51.059285,55.499271,15.255194,2.214521,29.760681,24.732187,78.404778,0.680237,190.634243,57.968577,963.701254,Severe
496,NaT,571.988300,629.313349,33.971877,49.545926,35.255735,14.617839,2.385924,28.363629,24.204462,77.529325,0.705796,194.679159,61.140436,962.810901,Severe
497,NaT,410.904046,702.229274,3.845862,52.024544,52.074945,13.998989,2.703408,32.956792,24.919254,81.849385,0.656507,197.854424,61.420218,963.033710,Severe
498,NaT,510.148393,551.481660,20.848115,48.293973,46.547960,15.489362,2.513495,30.787819,25.223937,75.096419,0.661409,203.286168,60.163099,961.946576,Severe
499,NaT,450.007278,587.518264,50.357062,45.877055,42.624375,15.158260,2.400524,32.747568,24.336505,74.161154,0.667413,194.443312,62.504044,963.599918,Severe

In [35]:
#droping data column as we have a synthetic data set now 
synthetic_df = synthetic_df.drop(columns=['Date'], errors='ignore')

In [36]:
synthetic_df

,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
0,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833,Moderate
1,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667,Moderate
2,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667,Moderate
3,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750,Poor
4,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,586.498152,659.311335,31.729843,51.059285,55.499271,15.255194,2.214521,29.760681,24.732187,78.404778,0.680237,190.634243,57.968577,963.701254,Severe
496,571.988300,629.313349,33.971877,49.545926,35.255735,14.617839,2.385924,28.363629,24.204462,77.529325,0.705796,194.679159,61.140436,962.810901,Severe
497,410.904046,702.229274,3.845862,52.024544,52.074945,13.998989,2.703408,32.956792,24.919254,81.849385,0.656507,197.854424,61.420218,963.033710,Severe
498,510.148393,551.481660,20.848115,48.293973,46.547960,15.489362,2.513495,30.787819,25.223937,75.096419,0.661409,203.286168,60.163099,961.946576,Severe
499,450.007278,587.518264,50.357062,45.877055,42.624375,15.158260,2.400524,32.747568,24.336505,74.161154,0.667413,194.443312,62.504044,963.599918,Severe

In [37]:
#column checks 
print(synthetic_df.columns)

Index(['PM2.5_µgm³', 'PM10_µgm³', 'NO_µgm³', 'NO2_µgm³', 'NOx_ppb', 'SO2_µgm³',
       'CO_mgm³', 'Ozone_µgm³', 'AT_C', 'RH_percent', 'WS_ms', 'WD_deg',
       'SR_Wmt2', 'BP_mmHg', 'AQI_Category'],
      dtype='object')

In [38]:
synthetic_df.head()

,PM2.5_µgm³,PM10_µgm³,NO_µgm³,NO2_µgm³,NOx_ppb,SO2_µgm³,CO_mgm³,Ozone_µgm³,AT_C,RH_percent,WS_ms,WD_deg,SR_Wmt2,BP_mmHg,AQI_Category
0,176.679583,293.727083,16.357500,33.182917,39.324583,10.389583,1.177917,15.869583,11.346250,72.005000,0.710833,174.558750,49.583750,974.870833,Moderate
1,180.665000,293.752500,20.056250,35.415000,44.370417,11.555417,1.162917,17.450000,10.869583,69.444583,0.677500,169.500000,62.596250,974.491667,Moderate
2,191.461250,306.088333,25.389583,38.743750,50.359167,9.502083,1.485000,15.040833,10.237083,79.782500,0.655000,167.399583,46.275417,974.446667,Moderate
3,215.310417,347.739583,28.622917,39.125417,50.938333,10.648333,1.319583,11.795417,10.414167,80.744167,0.767917,200.645000,34.486667,974.443750,Poor
4,159.162500,275.042500,24.269583,39.634583,46.040833,11.218750,1.270833,14.331250,11.354583,81.830833,0.698333,189.891667,27.805833,974.436250,Moderate

In [39]:
synthetic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PM2.5_µgm³    500 non-null    float64
 1   PM10_µgm³     500 non-null    float64
 2   NO_µgm³       500 non-null    float64
 3   NO2_µgm³      500 non-null    float64
 4   NOx_ppb       500 non-null    float64
 5   SO2_µgm³      500 non-null    float64
 6   CO_mgm³       500 non-null    float64
 7   Ozone_µgm³    500 non-null    float64
 8   AT_C          500 non-null    float64
 9   RH_percent    500 non-null    float64
 10  WS_ms         500 non-null    float64
 11  WD_deg        500 non-null    float64
 12  SR_Wmt2       500 non-null    float64
 13  BP_mmHg       500 non-null    float64
 14  AQI_Category  500 non-null    object
dtypes: float64(14), object(1)
memory usage: 58.7+ KB

In [40]:
synthetic_df.isnull().sum()

PM2.5_µgm³      0
PM10_µgm³       0
NO_µgm³         0
NO2_µgm³        0
NOx_ppb         0
SO2_µgm³        0
CO_mgm³         0
Ozone_µgm³      0
AT_C            0
RH_percent      0
WS_ms           0
WD_deg          0
SR_Wmt2         0
BP_mmHg         0
AQI_Category    0
dtype: int64

In [41]:
synthetic_df['AQI_Category'].value_counts()

AQI_Category
Satisfactory    143
Good             97
Moderate         80
Poor             60
Very Poor        60
Severe           60
Name: count, dtype: int64

In [42]:
# Due to class imbalance in Severe and Very Poor categories, synthetic samples were generated using distribution-based augmentation to achieve balanced multi-class training.

In [43]:
#so till here we have made the dataset clean and ready for machine learing
#converted hourly t daily
#dropped useless columns 
#checked missing values
#renamed column names 
#created aqi category (target variable)
#checked class distribution

In [44]:
synthetic_df.to_csv("Final_AQI_Balanced_Dataset.csv", index=False)

In [ ]:
#till nwo we have made a clean dataset now